# Generated by Django 2.1.5 on 2019-05-10 19:58

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_link', models.TextField(help_text='store link, e.g. playstore', max_length=255)),
                ('hits', models.CharField(help_text='number of hits on app', max_length=255)),
                ('photo', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('ad_status', models.BooleanField(default=False)),
            ],
        ),
    ]
