# Generated by Django 2.1.5 on 2019-05-10 20:53

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsdata',
            name='hits',
            field=models.CharField(help_text='number of hits on app', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adsdata',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/media/rizwan/WORK-DATA/Office_work/web_solution/django_tasks/unit_ads_system/MEDIA'), upload_to=''),
        ),
    ]
