# Generated by Django 2.1.5 on 2020-05-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Category', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adsdata',
            name='ready',
        ),
        migrations.AddField(
            model_name='adsdata',
            name='category',
            field=models.ForeignKey(help_text='Category of the ad', null=True, on_delete=django.db.models.deletion.CASCADE, to='adsapp.AdCategory'),
        ),
    ]
