# Generated by Django 2.1.5 on 2019-05-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0002_auto_20190510_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsdata',
            name='hits',
            field=models.CharField(blank=True, help_text='number of hits on app', max_length=255, null=True),
        ),
    ]
