# Generated by Django 2.1.5 on 2020-05-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0002_auto_20200503_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsdata',
            name='hit_link',
        ),
        migrations.AddField(
            model_name='adsdata',
            name='ads_hit_count',
            field=models.IntegerField(default=0, help_text='Ads hit count'),
        ),
    ]
