# Generated by Django 2.1.5 on 2019-06-02 19:12

from django.db import migrations, models
import django_dropbox_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0003_auto_20190510_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsdata',
            name='photo',
            field=models.ImageField(storage=django_dropbox_storage.storage.DropboxStorage(), upload_to='photos'),
        ),
    ]
