# Generated by Django 2.1.5 on 2019-08-07 18:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapp', '0004_auto_20190602_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsdata',
            name='studio_name',
            field=models.CharField(blank=True, help_text='Name of the studio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adsdata',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/rizwan/Desktop/heroku_apps/unity-ads-system/MEDIA'), upload_to='photos'),
        ),
    ]
